### ISSUE TITLE
comparing to other implementations

### ISSUE THREAD

**Issue by alexmyczko** [Seegras/screwtime#1]
what can you say about:

https://github.com/wolfcw/libfaketime
and
datefudge

feature wise?

**Comment by Seegras** [comment]
mine is a basic as it gets. libfaketime can do a lot more; datefudge also changes clock_gettime which mine doesn't (I could/should probably add that); and also allows to specify the time much more nicely; with mine you need to do it in the source. 

In the end, all of these can be circumvented by apps that load librt with dlopen after init. I had the idea to write a kernel-module to solve this, but didn't yet do it. Maybe somebody else wrote one?
